# Aljabar Liniear

In [5]:
import numpy as np

In [12]:
orders = np.array([
    [2,0,0,0],
    [1,0,2,4],
    [1,2,1,0],
    [4,6,0,2]
])
totals = np.array([20000, 32000, 20000, 61000])
prices = np.linalg.solve(orders,totals)   #linalg = linier algebra
prices

array([10000.,  2500.,  5000.,  3000.])

In [11]:
orders @ prices

array([20000., 32000., 20000., 61000.])

# Fungsi Universal

In [13]:
a, b = np.split(np.arange(1,11), 2) 

In [14]:
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [15]:
a +b

array([ 7,  9, 11, 13, 15])

In [16]:
b -a 

array([5, 5, 5, 5, 5])

In [17]:
a + 2

array([3, 4, 5, 6, 7])

In [18]:
a + np.repeat(2,5)

array([3, 4, 5, 6, 7])

In [19]:
# fungsi universal bisa dilihat di docs.scipy.org

### contoh latian 

In [24]:
x1 = np.arange(9.0). reshape((3,3))
x2 = np.arange(3.0)
x1,x2

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [25]:
np.add(x1,x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [27]:
np.add(x1, 2)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

# Operasi MAtrix Lainnya

In [3]:
# lanjut di numpy 1 lagi