# Import Numpy

In [14]:
import numpy as np
a = np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

# Creating Array

In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
print(np.arange(4))

[0 1 2 3]


In [22]:
print(np.arange(4))
print(np.arange(0,10,15))

[0 1 2 3]
[0]


In [10]:
arr = np.array([1,2,3,4,5,6])

# ADD, REMOVE, AND SHORT

In [25]:
arr = np.array([1,2,3,4,5,5,6])

In [28]:
np.append(arr, [7,8])

array([1, 2, 3, 4, 5, 5, 6, 7, 8])

In [29]:
np.delete(arr, 3)

array([1, 2, 3, 5, 5, 6])

In [30]:
np.sort(arr)

array([1, 2, 3, 4, 5, 5, 6])

# Shape and Size

In [31]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [32]:
array_example.ndim

3

In [33]:
array_example.size

24

In [34]:
array_example.shape

(3, 2, 4)

In [35]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [36]:
arr_one.ndim

2

In [37]:
arr_one.size

5

In [38]:
arr_one.shape

(1, 5)

# Reshape

In [39]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [40]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [41]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [43]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [44]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [45]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [46]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [47]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [48]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [49]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [50]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [52]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [53]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [54]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [56]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [59]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [60]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [61]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [62]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [63]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [64]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [65]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# BAsic Array Operation

In [68]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [69]:
b = np.array([[1, 1], [2, 2]])
b


array([[1, 1],
       [2, 2]])

In [70]:

# You can sum the rows

b.sum(axis=0)


array([3, 3])

In [71]:
b.sum(axis=1)

array([2, 4])

In [72]:
data = np.array([1, 2])
data

array([1, 2])

In [73]:
ones = np.ones(2)
ones

array([1., 1.])

In [74]:
data + ones

array([2., 3.])

In [75]:
data * data

array([1, 4])

In [76]:
data / data

array([1., 1.])

# Broadcasting

In [77]:
data * 2

array([2, 4])

# More Array Operation 

In [78]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [79]:
A.sum()


4.8595784

In [80]:
A.min()

0.05093587

In [81]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [82]:
A.max()

0.82485143

In [83]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [84]:
A.std()

0.21392120766089617

# Matrics

In [85]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.47516776, 0.67680384],
       [0.88835278, 0.2364653 ],
       [0.34343504, 0.0056189 ]])

In [86]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.41827715 0.30166383]
 [0.98579652 0.32580257]
 [0.48070997 0.56958294]]


# Matrix Arithmetic

In [87]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [88]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [89]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [90]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [91]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [92]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [93]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [94]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Agregation

In [95]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [96]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [97]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [98]:
print(data)


[[1 2]
 [3 4]
 [5 6]]


In [99]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [100]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [101]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# N-Dimensional Array

In [103]:
ndarr = np.array([[[1, 2], [3, 4]],              
                [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
