In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
iris = load_iris()

df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [3]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [4]:
df['target'].value_counts()

target
0.0    50
1.0    50
2.0    50
Name: count, dtype: int64

In [5]:
X = df.drop(columns = 'target')
y = df['target']

In [6]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: target, Length: 150, dtype: float64

In [8]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
logit = LogisticRegression()

logit.fit(X,y)

logit.score(X,y)

0.9733333333333334

In [10]:
knn = KNeighborsClassifier()

knn.fit(X,y)

knn.score(X,y)

0.9666666666666667

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [12]:
X_train.shape

(112, 4)

In [13]:
X_test.shape

(38, 4)

In [14]:
y_train.shape

(112,)

In [15]:
y_test.shape

(38,)

In [16]:
logit = LogisticRegression()
logit.fit(X_train, y_train)

y_pred = logit.predict(X_test)
accuracy_score(y_test, y_pred)

0.8947368421052632

In [17]:
y_pred_proba = logit.predict_proba(X_test)
y_pred = logit.predict(X_test)

In [18]:
y_pred

array([1., 1., 0., 2., 1., 1., 0., 1., 1., 2., 2., 2., 0., 0., 2., 2., 0.,
       1., 2., 2., 0., 1., 1., 1., 1., 1., 0., 1., 1., 2., 1., 2., 1., 0.,
       1., 0., 0., 1.])

In [19]:
y_pred_proba

array([[1.63974809e-01, 8.32525218e-01, 3.49997367e-03],
       [2.37307018e-02, 9.10763268e-01, 6.55060306e-02],
       [9.79283686e-01, 2.07160714e-02, 2.42315897e-07],
       [2.99370801e-04, 1.87174247e-01, 8.12526382e-01],
       [1.01362652e-03, 5.26919123e-01, 4.72067250e-01],
       [1.02781222e-02, 8.62504325e-01, 1.27217553e-01],
       [9.46304597e-01, 5.36943802e-02, 1.02280732e-06],
       [1.09202462e-02, 9.23206796e-01, 6.58729575e-02],
       [8.06939090e-03, 8.90659832e-01, 1.01270777e-01],
       [1.59245308e-04, 1.52469263e-01, 8.47371492e-01],
       [3.70414470e-03, 4.49787898e-01, 5.46507957e-01],
       [5.65328493e-04, 2.20653913e-01, 7.78780759e-01],
       [9.57195280e-01, 4.28033554e-02, 1.36504626e-06],
       [9.75236516e-01, 2.47633580e-02, 1.25832231e-07],
       [2.61929786e-05, 4.76368012e-02, 9.52337006e-01],
       [5.99378815e-04, 2.36857803e-01, 7.62542818e-01],
       [9.68515362e-01, 3.14840767e-02, 5.61545870e-07],
       [2.29220678e-02, 9.55119

In [21]:
logit.intercept_

array([  9.44907749,   2.77910869, -12.22818618])

In [24]:
X_train.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [25]:
logit.coef_

array([[-0.42294928,  0.77674428, -2.27754937, -0.98416382],
       [ 0.39280986, -0.48564851, -0.09064956, -0.8736908 ],
       [ 0.03013942, -0.29109577,  2.36819893,  1.85785462]])

In [26]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.9473684210526315

In [28]:
y_pred

array([1., 1., 0., 2., 2., 1., 0., 1., 1., 2., 2., 2., 0., 0., 2., 2., 0.,
       1., 2., 2., 0., 2., 1., 1., 1., 1., 0., 1., 1., 2., 1., 2., 1., 0.,
       1., 0., 0., 1.])

In [29]:
y_test

57     1.0
96     1.0
21     0.0
147    2.0
133    2.0
55     1.0
24     0.0
74     1.0
75     1.0
137    2.0
70     1.0
110    2.0
44     0.0
49     0.0
132    2.0
113    2.0
5      0.0
67     1.0
108    2.0
101    2.0
13     0.0
119    2.0
69     1.0
106    2.0
91     1.0
66     1.0
33     0.0
79     1.0
53     1.0
130    2.0
65     1.0
141    2.0
87     1.0
15     0.0
71     1.0
25     0.0
34     0.0
68     1.0
Name: target, dtype: float64